import { useEffect, useState } from "react";
import { type NextPage } from "next";
import { useRouter } from "next/navigation";
import Head from "next/head";
import { ErrorMessage, Field, Form, Formik } from "formik";

import { api } from "~/utils/api";
import { Title } from "./components/Title";

const Home: NextPage = () => {
  const [showOptionsModal, setShowOptionsModal] = useState(false);
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { push } = useRouter();
  const { mutate } = api.curl.createCurl.useMutation({
    onSuccess: (data) => {
      push(`${data.curlId}`);
    },
  });

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "k" && e.metaKey) {
        e.preventDefault();
        setShowOptionsModal(!showOptionsModal);
      }
      if (e.key === "Escape") {
        e.preventDefault();
        setShowOptionsModal(false);
      }
      if (e.key === "Enter" && e.shiftKey) {
        e.preventDefault();
        document.getElementById("submitPasteBin")?.click();
      }

      if (showOptionsModal) {
        e.preventDefault();
        switch (e.key) {
          case "1":
            document.getElementById("copyLinkToClipboard")?.click();
            break;
          case "2":
            document.getElementById("isEditable")?.click();
            break;
          default:
            break;
        }
      }
    }

    document.addEventListener("keydown", handleKeyDown);

    // Don't forget to clean up
    return function cleanup() {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [showOptionsModal]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b ">
        <Title />
        <Formik
          initialValues={{
            curlRequest: "",
            isEditable: true,
            copyLinkToClipboard: true,
          }}
          onSubmit={(values) => {
            mutate({
              curlRequest: values.curlRequest,
              isEditable: values.isEditable,
            });
          }}
        >
          <Form className="w-10/12">
            <div className="flex">
              <p className="mx-5 -mb-2 text-xs font-extralight tracking-widest">
                Built by{" "}
                <a
                  href="https://www.github.com/rupert648"
                  target="_blank"
                  className="underline"
                >
                  Rupert Carr
                </a>
              </p>
              <p className="m-auto mr-0 text-xs font-extralight tracking-widest">
                <a
                  href="https://www.twitter.com/rupert648"
                  target="_blank"
                  className="hover:underline"
                >
                  #️⃣ twitter
                </a>{" "}
                <a
                  href="https://www.buymeacoffee.com/rupertcarr"
                  target="_blank"
                  className="hover:underline"
                >
                  ☕ buy me a coffee
                </a>
                <a
                  href="https://www.github.com/rupert648"
                  target="_blank"
                  className="ml-1 hover:underline"
                >
                  🧑‍💻 github
                </a>
              </p>
            </div>
            <Field
              placeholder="Paste your sh*t here"
              id="curlRequest"
              name="curlRequest"
              as="textarea"
              className="m-4 h-[80vh] w-full resize-none rounded-lg border border-gray-300 p-4 focus:outline-none focus:ring-2 focus:ring-orange-400"
            />
            <ErrorMessage name="curlRequest" />
            <div className="flex items-center">
              <button
                className="m-4 flex max-w-xs flex-col gap-4 rounded-lg border border-gray-300 p-4 text-black hover:bg-black/5"
                onClick={() => setShowOptionsModal(true)}
                type="button"
              >
                <h3 className="text-1xl font-bold">
                  Options <span className="text-orange-400">(⌘K)</span>
                </h3>
              </button>
              <button
                className="flex max-w-xs flex-col gap-4 rounded-lg border border-gray-300 p-4 text-black hover:bg-black/5"
                type="submit"
                id="submitPasteBin"
              >
                <h3 className="text-1xl font-bold">
                  Create your Paste bin{" "}
                  <span className="text-orange-400">(⇧+Enter)</span>
                </h3>
              </button>
            </div>

            {showOptionsModal && (
              <div className="fixed inset-0 flex items-center justify-center bg-black/10">
                {}
                <div className="rounded-xl bg-white p-4">
                  <h3 className="text-1xl font-bold">Options</h3>
                  <div className="flex flex-col gap-2">
                    <label className="text-black">
                      <Field
                        type="checkbox"
                        name="copyLinkToClipboard"
                        id="copyLinkToClipboard"
                      />
                      Copy Link to clipboard
                      <span className="font-extralight">(1)</span>
                    </label>
                    <label className="text-black">
                      <Field
                        type="checkbox"
                        name="isEditable"
                        id="isEditable"
                      />
                      Editable
                      <span className="font-extralight">(2)</span>
                    </label>
                  </div>
                </div>
              </div>
            )}
          </Form>
        </Formik>
      </main>
    </>
  );
};

export default Home;
