import { type NextPage } from "next";
import { useRouter } from "next/navigation";
import Head from "next/head";
import { ErrorMessage, Field, Form, Formik } from "formik";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const { push } = useRouter();
  // TODO: do something with loading state
  const { mutate, error, isLoading } = api.curl.createCurl.useMutation({
    onSuccess: (data) => {
      push(`${data.curlId}`);
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Formik
          initialValues={{
            curlRequest: "",
            isEditable: true,
          }}
          onSubmit={(values) => {
            mutate({
              curlRequest: values.curlRequest,
              isEditable: values.isEditable,
            });
          }}
        >
          <Form className="w-10/12">
            <Field
              placeholder="Paste your curl command here"
              id="curlRequest"
              name="curlRequest"
              as="textarea"
              className="m-4 h-[80vh] w-full resize-none rounded-lg border border-gray-300 p-4 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <ErrorMessage name="curlRequest" />
            <label className="text-white">
              Editable
              <Field type="checkbox" name="isEditable" />
            </label>
            <button className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">Create your Curl Page →</h3>
            </button>
          </Form>
        </Formik>
      </main>
    </>
  );
};

export default Home;
